### PR TITLE
Subscan handling mainly for OTF mode.

### PR DESCRIPTION
**Pull request by demorest**
Still in progress so not totally ready to merge.

Basic plan is to group subscans under a single `ScanConfig` object as discussed in #12 rather than as independent scans.  This should help handling of OTF observations for realfast.  The main changes are:
- Some new OTF-related properties in `ScanConfig`
- The first subscan in a scan creates a `ScanConfig` object as before.  Additional subscans also have `ScanConfig` instance, these are collected in a list inside the first one.  The whole group can be accessed via `ScanConfig.subscans` property.
- `Controller.handle_config` is called when the first subscan has complete info (same as before).
- When additional subscans have updated info, `Controller.handle_subscan` is called instead.

Any of this can be changed if it doesn't work as we need it to..

### CODE REVIEW

**Comment by caseyjlaw** [comment]
This should work.
I can probably do my data read planning for each subscan. Each subscan will know far enough ahead to plan at least one read, so that should be fine.
Something like:
```
def handle_subscan(self, config):
    if config.otf:
        for ss in self.subscans:
            [get start and stop for all subscans]
        [calculate segments for reading]
        [submit any new segments]
        [remember submitted segments]
```

**Comment by demorest** [comment]
Ok, sounds good.  One thing to note that may not have been obvious is that there may already be a few subscans in the list the first time `handle_config` is called for a given scan.  `handle_config` is only called once, after this `handle_subscan` is called anytime the subscan info is updated.

**Comment by demorest** [comment]
Let me know if you think anything needs changing based on the tests today.  If not, I'll merge this in sometime soon.

**Comment by caseyjlaw** [comment]
I think the design makes sense and I can work with it. Feel free to merge.

**Comment by caseyjlaw** [comment]
I'm setting up the realfast logic for OTF. Now trying to think about whether `handle_config` or `handle_subscan` is a subset of the other or if they are just called in different situations.
Question: is `handle_subscan` called outside of OTF mode when an complete scan is defined?

I think the answer is no. If that is right, then it is not correct to think of one `handle` function as a subset of the other.

**Comment by demorest** [comment]
They are called in different situations:

As soon as a scan has "complete" info (including the stop time of the first subscan), `handle_config` is called.  After that, any time additional subscan info becomes available for that scan, `handle_subscan` is called.

`handle_subscan` will never be called for scans that only have a single subscan; this is the case for nearly all normal / non-OTF observations.

**Comment by caseyjlaw** [comment]
Ok, I have some realfast code that should be able to handle this at https://github.com/realfastvla/realfast/blob/otf/realfast/controllers.py#L218.
Still some work for me to properly do phase rotation, but I think we're close to being ready to test!

**Pull request merged**
